"$schema" = "https://schema.tauri.app/config/2"
productName = "openchad"
version = "0.1.18"
identifier = "com.openchad.app"
[build]
frontendDist = "./frontend"
[app]
withGlobalTauri = true
security.capabilities = ["default"]

[[app.windows]]
width = 1280
height = 720
title = "openchad"
center = true
decorations = false

# Overlay-specific settings
# resizable = false
# transparent = true
# alwaysOnTop = true
# skipTaskbar = true
# focusable = false       
# shadow = false
# contentProtected = true

maximized = true

[bundle]
icon = [
    "icons/icon.png",
    "icons/icon.ico",
]
